### PR TITLE
Gaitlyn malone noaa patch 1

### PR DESCRIPTION
**Pull request by GaitlynMalone-NOAA**
Merge request script to create example tables

### CODE REVIEW

**Review by SarinaAtkinson-NOAA — CHANGES_REQUESTED** [review]
Can you please remove the step where you hardcode a test file and save it as a csv and RDS file. I think here we should be reading directly from the MH Data Log RDS file. In the past, the reason why people were confused with test was because they thought the test.csv file was the full dataset and I want to avoid that here.

**Comment by GaitlynMalone-NOAA** [comment]
Can you please remove the step where you hardcode a test file and save it as a csv and RDS file. I think here we should be reading directly from the MH Data Log RDS file. In the past, the reason why people were confused with test was because they thought the test.csv file was the full dataset and I want to avoid that here.

I've removed the portion of the code that created a test file and have read in the RDS. Additionally I've changed the name of the RDS file to include "MH_DL" instead of "MH_AL"

**Review by SarinaAtkinson-NOAA — APPROVED** [review]
Thanks Gaitlyn! For the new NH Data Log RDS file, does it also include all variables or not yet?

**Comment by GaitlynMalone-NOAA** [comment]
Not yet. Working on that now. Should I do it as a new pull request?

**Comment by SarinaAtkinson-NOAA** [comment]
Yes, that sounds good! I will merge this now and we will do another pull request for Data Log variables

**Pull request merged**
